// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vR1hAb2jq8HN4hNqOjmdgRYsbMOrons',
    appId: '1:11352248698:web:944f943c5c8cda795846c3',
    messagingSenderId: '11352248698',
    projectId: 'hackathon-b0315',
    authDomain: 'hackathon-b0315.firebaseapp.com',
    storageBucket: 'hackathon-b0315.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz89K1YGc7ekuqrHchvwLrowJrrEmDA1E',
    appId: '1:11352248698:android:07ebf3f7c6d848cd5846c3',
    messagingSenderId: '11352248698',
    projectId: 'hackathon-b0315',
    storageBucket: 'hackathon-b0315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnYPBRYgBCqPLN6jCms3FZYLzRyxshDI',
    appId: '1:11352248698:ios:3740f2b5e931dc045846c3',
    messagingSenderId: '11352248698',
    projectId: 'hackathon-b0315',
    storageBucket: 'hackathon-b0315.appspot.com',
    iosBundleId: 'com.example.mySmartCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOnYPBRYgBCqPLN6jCms3FZYLzRyxshDI',
    appId: '1:11352248698:ios:5c539aa2e70ea35e5846c3',
    messagingSenderId: '11352248698',
    projectId: 'hackathon-b0315',
    storageBucket: 'hackathon-b0315.appspot.com',
    iosBundleId: 'com.example.mySmartCity.RunnerTests',
  );
}
